model:
    arch: unet
    in_channels: 4
data:
    dataset: diydata
    train_split: train_aug
    val_split: val
    img_rows: 400
    img_cols: 'same'
    path: D:\yinxcao\height\sample
    n_class: 1
    n_maxdisp: 192
training:
    epochs: 300
    batch_size: 16
    learning_rate: 0.001
    resume: ''
    device: 'cuda'

