model:
    arch: tlcnetu
data:
    dataset: diydata
    train_split: train_aug
    val_split: val
    img_rows: 400
    img_cols: 'same'
    path: E:\yinxcao\us\sample
    n_class: 1
    n_maxdisp: 192
training:
    epochs: 300
    batch_size: 16
    learning_rate: 0.001
    resume: 'runs\\tlcnetu_zy3bh_us_pre_loss\\V2\\finetune_150.tar'
    device: 'cuda'
savepath: ''

